name: Update Stock Data

on:
  schedule:
    - cron: '*/5 * * * *'  # 5분마다 실행
  workflow_dispatch:  # 수동 실행 옵션

# GitHub Actions 권한 설정
permissions:
  contents: write
  pull-requests: write

# 동시 실행 방지 설정
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  update-stock-data:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # 최대 10분 후 타임아웃
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests beautifulsoup4

      - name: Run stock data collector
        run: |
          python stock.py
          cat stock_consensus.csv  # 수집된 데이터 확인

      - name: Commit and push if changed
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update stock data $(date '+%Y-%m-%d %H:%M:%S')" && git push) 