name: Update Stock Data

on:
  schedule:
    - cron: '0 * * * *'  # 매시 정각에 실행
  workflow_dispatch:      # 수동 실행 가능

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create credentials file
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: echo "$GOOGLE_CREDENTIALS" > credentials.json
    
    - name: Run update script
      run: python naver_stock_test.py
      
    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add stock_consensus.csv
        git diff --quiet && git diff --staged --quiet || git commit -m "Update stock data"
        git push 